# Generated by Django 3.2.5 on 2021-07-22 19:27

from django.db import migrations, models
import vision.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagesessn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('myfiles', models.FileField(upload_to=vision.models.Imagesessn.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Visionuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default={'currpg': 0, 'currvw': 0, 'dtsloc': 0, 'labels': {}, 'numitems': 0})),
                ('currimage', models.JSONField(default={})),
            ],
        ),
    ]
