# Generated by Django 3.2.5 on 2021-08-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionuser',
            name='currimage',
        ),
        migrations.AlterField(
            model_name='visionuser',
            name='metadata',
            field=models.JSONField(),
        ),
    ]
